name: MultiRequired
on: [pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      paths: ${{ steps.filter.outputs.paths }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          paths:
            - "path1/**"
            - "path2/**"

  build:
    name: Multi real build
    needs: changes
    if: ${{ needs.changes.outputs.paths == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do build
        run: 'echo "Doing a real build"'

  sentinel:
    name: Multi Sentinel
    needs: [build]
    if: ${{ success() || failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Failed
        if: ${{ contains(needs.*.result, 'failure')}}
        run: exit 1
      - name: Success
        run: 'echo "All good"'