name: MultiRequired
on:
  pull_request:
    paths:
      - "path1/**"
      - "path2/**"
jobs:
  build:
    name: Multi real build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do build
        run: 'echo "Doing a real build"'

